AgoraApi\Application\Entities\RoleRoutes:
    type: entity
    table: role_routes
    indexes:
        fk_role_routes_role_id_roles_id_idx:
            columns:
                - role_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        route:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        updatedAt:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: updated_at
        createdAt:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: created_at
    manyToOne:
        role:
            targetEntity: AgoraApi\Application\Entities\Roles
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                role_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
