AgoraApi\Application\Entities\Tasks:
    type: entity
    table: tasks
    indexes:
        fk_contact_id_contact_id_idx_idx_idx:
            columns:
                - contact_id
        fk_assigned_contact_id_contact_id_idx_idx_idx:
            columns:
                - assigned_contact_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        statusId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: status_id
        description:
            type: text
            nullable: false
            length: 255
            options:
                fixed: false
        dateDue:
            type: datetime
            nullable: true
            column: date_due
        dateCompleted:
            type: datetime
            nullable: true
            column: date_completed
        updatedAt:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: updated_at
        createdAt:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: created_at
    manyToOne:
        assignedContact:
            targetEntity: AgoraApi\Application\Entities\Contact
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                assigned_contact_id:
                    referencedColumnName: id
            orphanRemoval: false
        contact:
            targetEntity: AgoraApi\Application\Entities\Contact
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                contact_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
