AgoraApi\Application\Entities\Notes:
    type: entity
    table: notes
    indexes:
        fk_contact_id_contact_id_idx_idx:
            columns:
                - contact_id
        fk_added_by_contact_id_contact_id_idx_idx:
            columns:
                - added_by_contact_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        note:
            type: blob
            nullable: false
            length: 65535
            options:
                fixed: false
        updatedAt:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: updated_at
        createdAt:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: created_at
    manyToOne:
        addedByContact:
            targetEntity: AgoraApi\Application\Entities\Contact
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                added_by_contact_id:
                    referencedColumnName: id
            orphanRemoval: false
        contact:
            targetEntity: AgoraApi\Application\Entities\Contact
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                contact_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
