AgoraApi\Application\Entities\Entities:
    type: entity
    table: entities
    indexes:
        entities_name:
            columns:
                - name
        entities_identifier:
            columns:
                - identifier
        fk_industry_id_industries_id:
            columns:
                - industry_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        identifier:
            type: string
            nullable: false
            length: 15
            options:
                fixed: false
        name:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
        status:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
        state:
            type: string
            nullable: false
            length: 3
            options:
                fixed: false
        postCode:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
            column: post_code
        expiresAt:
            type: datetime
            nullable: false
            column: expires_at
        enabled:
            type: boolean
            nullable: false
        createdAt:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: updated_at
    manyToOne:
        industry:
            targetEntity: AgoraApi\Application\Entities\Industries
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                industry_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
