routes:
  address:
    methods:
    - GET
    actions:
    - 'Agora\Bundles\Address\Controller\Controller:fetchOne'
    priority: 0
    pattern: '/api/v1/address[/{id}]'
    middleware:
    - 'TokenAuthentication'
    roles:
    - ['User', 'Admin']
  login:
    methods:
    - POST
    actions:
    - 'Agora\Bundles\Contact\Controller\Controller:authenticateOne'
    priority: 0
    pattern: 
    - '/api/v1/user/login'
    middleware:
    -
  industries:
    methods:
    - GET
    - POST
    - PUT
    - DELETE
    actions:
    - 'Agora\Bundles\Industries\Controller\Controller:autoComplete'
    - 'Agora\Bundles\Industries\Controller\Controller:onAdd'
    - 'Agora\Bundles\Industries\Controller\Controller:onUpdate'
    - 'Agora\Bundles\Industries\Controller\Controller:onDelete'
    priority: 0
    pattern: 
    - '/api/v1/industries/{description}'
    - '/api/v1/admin/industry'
    - '/api/v1/admin/industry/{id}'
    - '/api/v1/admin/industry/{id}'
    middleware:
    - 'TokenAuthentication'
    - 'TokenAuthentication'
    - 'TokenAuthentication'
    - 'TokenAuthentication'
    roles:
    - ['User', 'Admin']
    - ['Admin']
    - ['Admin']
    - ['Admin']   
  location:
    methods:
    - GET
    - POST
    - PUT
    - DELETE    
    actions:
    - 'Agora\Bundles\Locations\Controller\Controller:onGet'
    - 'Agora\Bundles\Locations\Controller\Controller:onAdd'
    - 'Agora\Bundles\Locations\Controller\Controller:onUpdate'
    - 'Agora\Bundles\Locations\Controller\Controller:onDelete'    
    priority: 0
    pattern: 
    - '/api/v1/location/{offset}/{industry}'
    - '/api/v1/location'
    - '/api/v1/location'
    - '/api/v1/location/{id}'
    middleware:
    - 'TokenAuthentication'
    - 'TokenAuthentication'
    - 'TokenAuthentication'
    - 'TokenAuthentication'
    roles:
    - ['User', 'Admin']
    - ['User', 'Admin']
    - ['User', 'Admin']
    - ['User', 'Admin']       
  roles:
    methods:
    - GET
    - POST
    - PUT
    - DELETE    
    actions:
    - 'Agora\Bundles\Roles\Controller\Controller:onGet'
    - 'Agora\Bundles\Roles\Controller\Controller:onAdd'
    - 'Agora\Bundles\Roles\Controller\Controller:onUpdate'
    - 'Agora\Bundles\Roles\Controller\Controller:onDelete'            
    priority: 0
    pattern: 
    - '/api/v1/roles/{offset}[/{id}]'
    - '/api/v1/admin/role'
    - '/api/v1/admin/role'
    - '/api/v1/admin/role/{id}'
    middleware:
    - 'TokenAuthentication'
    - 'TokenAuthentication'
    - 'TokenAuthentication'
    - 'TokenAuthentication'
    roles:
    - ['Guest', 'User', 'Admin']
    - ['Admin']
    - ['Admin']
    - ['Admin']  
  contact:
    methods:
    - GET
    - POST
    - PUT
    - DELETE 
    actions:
    - 'Agora\Bundles\Contact\Controller\Controller:onGet'
    - 'Agora\Bundles\Contact\Controller\Controller:onAdd'
    - 'Agora\Bundles\Contact\Controller\Controller:onUpdate'
    - 'Agora\Bundles\Contact\Controller\Controller:onDelete'
    priority: 0
    pattern: 
    - '/api/v1/admin/users'
    - '/api/v1/user'
    - '/api/v1/user'
    - '/api/v1/admin/user/{id}'
    middleware:
    - 'TokenAuthentication'
    - 'TokenAuthentication'
    - 'TokenAuthentication'
    - 'TokenAuthentication'
    roles:
    - ['Admin']
    - ['Guest', 'User', 'Admin']
    - ['User', 'Admin']
    - ['Admin']
  pages:
    methods:
    - GET
    - POST
    - PUT
    - DELETE 
    actions:
    - 'Agora\Bundles\Pages\Controller\Controller:onGet'
    - 'Agora\Bundles\Pages\Controller\Controller:onAdd'
    - 'Agora\Bundles\Pages\Controller\Controller:onUpdate'
    - 'Agora\Bundles\Pages\Controller\Controller:onDelete'
    priority: 0
    pattern: 
    - '/api/v1/pages'
    - '/api/v1/admin/page'
    - '/api/v1/admin/page'
    - '/api/v1/admin/page/{id}'
    middleware:
    - 'TokenAuthentication'
    - 'TokenAuthentication'
    - 'TokenAuthentication'
    - 'TokenAuthentication'
    roles:
    - ['Guest', 'User', 'Admin']
    - ['User', 'Admin']
    - ['User', 'Admin']
    - ['Admin']  