'@include': parameters.doctrine.yaml
cors:
  origin: 
  - 'chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop'
  - 'http://localhost:8080'
  - 'http://localhost:8000'
  methods:
  - 'OPTIONS'
  - 'GET'
  - 'POST'
  - 'PUT'
  - 'PATCH'
  - 'DELETE'
  - 'REQUEST'
  headers.allow: 
  - 'X-Requested-With'
  - 'Content-Type'
  - 'Accept'
  - 'Origin'
  - 'Authorization'
  headers.expose:
  -
  credentials: true
  cache: 86400
  error: null
  logger: null